---
title: "TSA: Forecasting Competition"
author: "Hannah Schofield & Sebrina Zu"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---
```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
#library(xlsx)
library(readxl)
```

```{r}
#Loading data
load <- read_excel("Competition/Data/load.xlsx")
relative_humidity <- read_excel("Competition/Data/relative_humidity.xlsx")
temperature<-read_excel("Competition/Data/temperature.xlsx")
```

```{r}
#convert hourly to daily averages 
load_daily <- load %>% 
  mutate(daily_average=rowMeans(load[,3:26],na.rm=TRUE))  %>% 
  select(date, daily_average)


#Temperature daily average
temperature_daily <- temperature %>% 
  mutate(average=rowMeans(temperature[,3:30],na.rm=TRUE))  %>% 
  select(date, average)%>%
  group_by(date) %>%
  summarize(daily_temp = sum(average))

#Humidity daily average
humidity_daily <- relative_humidity %>% 
  mutate(average_h=rowMeans(relative_humidity[,3:30],na.rm=TRUE))  %>% 
  select(date, average_h)%>%
  group_by(date) %>%
  summarize(daily_humid = sum(average_h))
```

```{r}
par(mfrow=c(1,2))
ACF_Plot <- Acf(load_daily$daily_average, lag = 40, plot = TRUE,main="")
PACF_Plot <- Pacf(load_daily$daily_average, lag = 40, plot = TRUE,main="")
par(mfrow=c(1,1))

```

```{r} 
#convert to time series 
ts_avgDaily <- msts(load_daily$daily_average, 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,1,1))

```

```{r}
#create test and train data subsets for forecasting
n_for = 365
ts_avgDaily_train <- subset(ts_avgDaily,end = length(ts_avgDaily)-n_for)

ts_avgDaily_test <- subset(ts_avgDaily,start = length(ts_avgDaily)-n_for)

autoplot(ts_avgDaily_train)
autoplot(ts_avgDaily_test)

```

```{r}
df_list = list(temperature_daily,humidity_daily,load_daily) 
exog_data<-df_list %>% reduce(full_join, by='date')
exog_ts<-msts(exog_data[,2:3], 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,1,1))
n_for = 365
exog_train <- head(exog_ts, n=nrow(exog_ts)-n_for)

exog_test <- tail(exog_ts,n=n_for+1)

```


```{r ETS}
ETS_fit <-  stlf(ts_avgDaily_train,h=365)

#Plot foresting results
autoplot(ETS_fit) + ylab("Load")

#Plot model + observed data
autoplot(ts_avgDaily) +
  autolayer(ETS_fit, series="STL + ETS",PI=FALSE) +
  ylab("Load")

ETS_fit_2010<-stlf(ts_avgDaily,h=59)

autoplot(ETS_fit_2010)

ETS_fit_2010
```

```{r ARIMA}

ARIMA_Four_fit <- auto.arima(ts_avgDaily_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_avgDaily_train, 
                                          K=c(2,12)))

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMA_Four_for <- forecast(ARIMA_Four_fit,
                           xreg=fourier(ts_avgDaily_train,
                                        K=c(2,12),
                                        h=365),
                                        h=365) 

#Plot foresting results
autoplot(ARIMA_Four_for) + ylab("Load")

#Plot model + observed data
autoplot(ts_avgDaily) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER",PI=FALSE) +
  ylab("Load")

```

```{r}
ARIMA_Four_fit_2010 <- auto.arima(ts_avgDaily, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_avgDaily, 
                                          K=c(2,12)))

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMA_Four_for_2010 <- forecast(ARIMA_Four_fit_2010,
                           xreg=fourier(ts_avgDaily,
                                        K=c(2,12),
                                        h=59),
                                        h=59) 

#Plot foresting results
autoplot(ARIMA_Four_for) + ylab("Load")

#Plot model + observed data
autoplot(ts_avgDaily) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER",PI=FALSE) +
  ylab("Load")

```


```{r NN}
#NN_fit <- nnetar(ts_avgDaily_train,p=1,P=1)
NN_fit <- nnetar(ts_avgDaily_train,p=1,P=0,xreg=fourier(ts_avgDaily_train, K=c(2,12)))

#NN_for <- forecast(NN_fit, h=365) 
NN_for <- forecast(NN_fit, h=365,xreg=fourier(ts_avgDaily_train, K=c(2,12),h=365))

#Plot foresting results
autoplot(NN_for) +
  ylab("Load") 

#Plot model + observed data
autoplot(ts_avgDaily) +
  autolayer(NN_for, series="Neural Network",PI=FALSE)+
  ylab("Load") 

```

```{r}
#NN_fit <- nnetar(ts_avgDaily_train,p=1,P=1)
NN_fit_2010 <- nnetar(ts_avgDaily,p=1,P=0,xreg=fourier(ts_avgDaily, K=c(2,12)))

#NN_for <- forecast(NN_fit, h=365) 
NN_for_2010 <- forecast(NN_fit_2010, h=59,xreg=fourier(ts_avgDaily, K=c(2,12),h=59))

```


```{r TBATS}
# TBATS can take time to fit
TBATS_fit <- tbats(ts_avgDaily_train)

TBATS_for <- forecast(TBATS_fit, h=n_for)

#Plot foresting results
autoplot(TBATS_for) +
  ylab("Load") 

#Plot model + observed data
autoplot(ts_avgDaily) +
  autolayer(TBATS_for, series="TBATS",PI=FALSE)+
  ylab("Load") 

```

```{r SARIMA}
SARIMA_autofit <- auto.arima(ts_avgDaily_train)

SARIMA_for <- forecast(SARIMA_autofit,h=n_for)

#Plot foresting results
autoplot(SARIMA_for) +
  ylab("Load") 

#Plot model + observed data
autoplot(ts_avgDaily) +
  autolayer(SARIMA_for, series="SARIMA",PI=FALSE)+
  ylab("Load") 
```

```{r SSES}
#SSES_seas <- es(ts_avgDaily_train,h=n_for,holdout=FALSE)

#SS_seas <- StructTS(ts_avgDaily_train,
                    #type="BSM",fixed=c(0,0.001,0.3,NA)) 
```

```{r}
ARIMAX_fit_train <- auto.arima(ts_avgDaily_train, 
                             seasonal=FALSE, 
                             lambda=0,
                            xreg=cbind(exog_train[,1],exog_train[,2],fourier(ts_avgDaily_train,K=c(2,6)))
                         )

Exog_fit_temp_train<-auto.arima(exog_train[,1])
Exog_fit_humid_train<-auto.arima(exog_train[,2])
Temp_for_train<-forecast(Exog_fit_temp_train,h=365)
Humid_for_train<-forecast(Exog_fit_humid_train,h=365)


ARIMAX_Four_for_train <- forecast(ARIMAX_fit_train,
                           xreg=cbind(Temp_for_train$mean,Humid_for_train$mean,fourier(ts_avgDaily_train,K=c(2,6),h=365)),
                                        h=365) 


```


```{r Exogenous Variables}
ARIMAX_fit <- auto.arima(ts_avgDaily, 
                             seasonal=FALSE, 
                             lambda=0,
                            xreg=cbind(exog_ts[,1],exog_ts[,2],fourier(ts_avgDaily,K=c(2,12)))
                         )

Exog_fit_temp<-auto.arima(exog_ts[,1])
Exog_fit_humid<-auto.arima(exog_ts[,2])
Temp_for<-forecast(Exog_fit_temp,h=59)
Humid_for<-forecast(Exog_fit_humid,h=59)

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMAX_Four_for <- forecast(ARIMAX_fit,
                           xreg=cbind(Temp_for$mean,Humid_for$mean,fourier(ts_avgDaily,K=c(2,12),h=59)),
                                        h=59) 
```

```{r}
#NN_fit <- nnetar(ts_avgDaily_train,p=1,P=1)
NNX_fit_train <- nnetar(ts_avgDaily_train,p=1,P=0,xreg=cbind(exog_train[,1],exog_train[,2],fourier(ts_avgDaily_train,K=c(2,6))))

NN_fit_temp_train<-nnetar(exog_train[,1])
NN_fit_humid_train<-nnetar(exog_train[,2])
NN_Temp_for_train<-forecast(NN_fit_temp_train,h=365)
NN_Humid_for_train<-forecast(NN_fit_humid_train,h=365)

#NN_for <- forecast(NN_fit, h=365) 
NNX_for_train <- forecast(NNX_fit_train,xreg=cbind(NN_Temp_for_train$mean,NN_Humid_for_train$mean,fourier(ts_avgDaily_train,K=c(2,6),h=365)),h=365)


```

```{r}
#NN_fit <- nnetar(ts_avgDaily_train,p=1,P=1)
NNX_fit <- nnetar(ts_avgDaily,p=1,P=0,xreg=cbind(exog_ts[,1],exog_ts[,2],fourier(ts_avgDaily,K=c(2,6))))

NN_fit_temp<-nnetar(exog_ts[,1])
NN_fit_humid<-nnetar(exog_ts[,2])
NN_Temp_for<-forecast(NN_fit_temp,h=59)
NN_Humid_for<-forecast(NN_fit_humid,h=59)

#NN_for <- forecast(NN_fit, h=365) 
NNX_for <- forecast(NNX_fit,xreg=cbind(NN_Temp_for$mean,NN_Humid_for$mean,fourier(ts_avgDaily,K=c(2,6),h=59)),h=59)
```


```{r scores}
#Model 1: STL + ETS
ETS_scores <- accuracy(ETS_fit$mean,ts_avgDaily_test)  

#Model 2: ARIMA + Fourier 
ARIMA_scores <- accuracy(ARIMA_Four_for$mean,ts_avgDaily_test)

# Model 3:  Neural Network 
NN_scores <- accuracy(NN_for$mean,ts_avgDaily_test)

## Model 4:  TBATS 
TBAT_scores <- accuracy(TBATS_for$mean,ts_avgDaily_test)

# Model 5:  SARIMA 
SARIMA_scores <- accuracy(SARIMA_for$mean,ts_avgDaily_test)

# Model 6:  SSES
#SSES_scores <- accuracy(SSES_seas$forecast,ts_avgDaily_test)

# Model 7:  BSM 
#SS_scores <- accuracy(SS_for$mean,ts_avgDaily_test)

# Model 8:  ARIMAX
ARIMAX_scores<- accuracy(ARIMAX_Four_for_train$mean,ts_avgDaily_test)

#Model 9: NNX
NNX_scores<- accuracy(NNX_for_train$mean,ts_avgDaily_test)
```


```{r RMSE}
#create data frame
scores <- as.data.frame(
  rbind(ETS_scores, ARIMA_scores, NN_scores,TBAT_scores,SARIMA_scores,ARIMAX_scores,NNX_scores))

row.names(scores) <- c("STL+ETS", "ARIMA+Fourier", "NN","TBAT","SARIMA","ARIMAX","NNX")

#choose model with lowest MAPE
best_model_index <- which.min(scores[,"MAPE"])
cat("The best model by MAPE is:", row.names(scores[best_model_index,]))  

```

```{r compare}
autoplot(ts_avgDaily_test) +
  autolayer(ETS_fit, PI=FALSE, series="STL+ETS") +
  autolayer(ARIMA_Four_for, PI=FALSE, series="ARIMA + Fourier") +
  autolayer(NN_for,PI=FALSE, series="NN") +
  ylab("Daily Load") +
  guides(colour=guide_legend(title="Forecast"))

```

```{r}
#convert to submission format 

forecastRange <- seq(as.Date("2011-01-01"), as.Date("2011-02-28"), by="days")
forecastDat<- ARIMAX_Four_for$mean
submission <- data.frame(forecastRange, forecastDat)
colnames(submission)<-c("date","load")
write.csv(submission, file = "submission_schofield_zu_ARIMAX.csv",row.names = FALSE)

```

```{r}
forecastDat3<- NN_for_2010$mean
submission <- data.frame(forecastRange, forecastDat3)
colnames(submission)<-c("date","load")
write.csv(submission, file = "submission_schofield_zu_NN.csv",row.names = FALSE)

```


```{r}
#convert to submission format 

forecastRange <- seq(as.Date("2011-01-01"), as.Date("2011-02-28"), by="days")
forecastDat2<- NNX_for$mean
submission <- data.frame(forecastRange, forecastDat2)
colnames(submission)<-c("date","load")
write.csv(submission, file = "submission_schofield_zu_NNX.csv",row.names = FALSE)

```
```

